### ISSUE TITLE
Ensuring no information loss

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#43] opened 2024-07-18 10:13 UTC
In #39, we shuffled things around a bit. It wasn't clear what the source of truth prior to #39 was meant to be, was it a) `input4MIPs_source_id.json` or b) `src/240701_2137_comp.json.7z`? @durack1 I think this is a question for you.

To ensure that there was no loss of new information (see also comment here: https://github.com/PCMDI/input4MIPs_CVs/pull/39#issuecomment-2235420403), we created a `legacy` folder. This has all the information as it was in `main` prior to merging #39.

The question now is, what is the source of truth? Once we know that, we can make sure that we are capturing it correctly and then delete the legacy folder.

**Comment by vnaik60** [comment] 2024-07-18 13:03
@znichollscr @durack1 https://pcmdi.github.io/input4MIPs_CVs/docs/input4MIPs_source_id.html is not working anymore. Is there a new pointer? Thanks!

**Comment by durack1** [comment] 2024-07-18 13:07
> what is the source of truth?

The source of truth, is the `src/240701_2137_comp.json.7z` contents first, with any overwrites from `input4MIPs_source_id.json` afterward, as a number of entries had been updated, correcting erroneous of missing ESGF index info.

Is that what we now have in `main`?

@vnaik60, @znichollscr has updated the repo, so point your browser to https://pcmdi.github.io/input4MIPs_CVs/docs/input4MIPs_datasets, which provides more comprehensive file-level (not just source_id/dataset) info, so from ~200 to 5885 searchable entries. We still have a couple of kinks to work out, but we're getting close

**Comment by vnaik60** [comment] 2024-07-18 13:11
Thanks @durack1. This is great. Will you be changing the "publication status" options to published, prototype etc? Now it is all CMIP.

**Comment by durack1** [comment] 2024-07-18 13:18
@vnaik60 looks like you've identified a problem, "publication status" should be either "Published" (ESGF data available) or "Registered" (included in source_id registration, but no data live). There are also some problems with the datetime entries, some are None, and we've also lost the download links...

**Comment by vnaik60** [comment] 2024-07-18 13:21
Yes for all those @durack1.  Expected I guess as you rebuild, break and fix :-).

**Comment by znichollscr** [comment] 2024-07-18 13:51
> Expected I guess as you rebuild, break and fix :-)

Yes :)

@durack1 is this something you can/want to fix as part of #41 or do you want me to look at this specifically now?

**Comment by durack1** [comment] 2024-07-25 20:17
I think this is now effectively a dupe of #41. I'll close proactively.

What we're hoping to do here is merge information from multiple sources, identify inconsistencies and get them fixed from their upstream sources - so ESGF SOLR input4MIPs index, the file trees themselves, and the registered information awaiting for new files to land.

Work first to get the new (CMIP6Plus) data correct, and then work through the CMIP6 entries once the new stuff is in good shape

**Closed by durack1** 2024-07-25 20:17 UTC
