### ISSUE TITLE
Registering institutions

### ISSUE THREAD

**Issue by znicholls** [PCMDI/input4MIPs_CVs#14] opened 2024-04-24 01:38 UTC
Can be closed as this is a duplicate of https://github.com/PCMDI/input4MIPs_CVs/issues/8 

~There doesn't appear to be an obvious place to register institutions. In the source IDs, they are a field, but there is no `*instution_IDs.json` file in this repo.~

~Are they instead meant to be registered instead in https://github.com/PCMDI/mip-cmor-tables/blob/main/MIP_institutions.json or https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_institution_id.json#L23?~

~@durack1 have I understood correctly or am I missing something?~

**Comment by znichollscr** [comment] 2024-04-24 03:00
Clsoing as duplicate of #8

**Comment by durack1** [comment] 2024-05-01 23:08
@znicholls sorry, you can't close yourself? Closing

**Closed by durack1** 2024-05-01 23:08 UTC
